language: nix
sudo: true

env:
  - EMACS_CI=emacs-25-3
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-snapshot

install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  - sudo apt-get install texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended texlive-latex-base texlive-generic-recommended golang
  - go get -u github.com/vbatts/git-validation

script:
  - make test
